version: "3"
services:
  haystack:
    image: "haystack:latest"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - elasticsearch
  elasticsearch:
    # This will start an empty elasticsearch instance (so you have to add your documents yourself)
    image: "elasticsearch:7.6.2"
    # If you want a demo image instead that is "ready-to-query" with some indexed Game of Thrones articles:
    # image: "deepset/elasticsearch-game-of-thrones"
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
